### ISSUE TITLE
Enable lambda warmup for all applicable lambdas

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#171]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

Recently, a fork of this repository ran into a real issue.  They had pushed changes to a lambda function and it had passed in their main branch.  Upon promoting to a higher environment, the lambda failed to deploy.

The error had to do with the warmup plugin being unhappy about something.  This issue is not about the specific error.  Rather, this issue is to address why this error succeeded in the main branch but failed later.  

The root cause is that the warmup plugin's enablement is conditional.  Currently, the deploy looks for an SSM parameter that indicates a generic "infrastructure type".  Example [here](https://github.com/CMSgov/macpro-quickstart-serverless/blob/master/services/app-api/serverless.yml#L32).  By default, warmup is disabled.  Optionally, it is turned on.  In the fork's scenario listed above, the higher env had warmup enabled.

This issue is calls for the global enablement of warmup.  However, setting the configuration of warmup (how often and how many warmup invocations should occur) should still be configurable.  So, warmup can never be shut off, but we can optionally warmup more or often.

## Proposed Approach

The current logic to enable/disable warmup should be removed.
The configuration of warmup (example: https://github.com/CMSgov/macpro-quickstart-serverless/blob/master/services/app-api/serverless.yml#L44-L48) should have defaults but be configurable via SSM.
For example:
```
warmup:
  enabled: true
  role: LambdaWarmupRole
  vpc: false
  events:
    - schedule: ${ssm:/configuration/${self:custom.stage}/warmup/schedule~true, ssm:/configuration/default/warmup/schedule~true, rate(4 minutes)}
  timeout: 20
  prewarm: true
  concurrency: ${ssm:/configuration/${self:custom.stage}/warmup/concurrency~true, ssm:/configuration/default/warmup/concurrency~true, 5}
  folderName: node_modules/serverless-bundle/src/_warmup
  cleanFolder: false
```

## Value

Enabling warmup globally brings development environments closer to production's state.  Errors should be found sooner, in development/main, rather than in higher environments.

## AC:

- Warmup is enabled anywhere warmup is used.
- The configuration for warmup (example: https://github.com/CMSgov/macpro-quickstart-serverless/blob/master/services/app-api/serverless.yml#L44-L48) has sensible default values.
- The configuration for warmup can be configured using the SSM pattern used for other environment specific options.
